<a href="https://colab.research.google.com/github/Bavesh-08/fake-news-classifier-using-LSTM/blob/main/Fake_News_Classifier_Using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

pf=pd.read_csv('/content/fake_news.csv', on_bad_lines='skip', engine='python')

pf.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1

In [ ]:
# checking is there is any null values

pf.isnull().sum()

id          0
title      64
author    244
text        6
label       0
dtype: int64

In [ ]:
# droping the null values

pf=pf.dropna()

In [ ]:
# spliting the dependent and independent values

x=pf.drop('label',axis=1)

y=pf['label']

In [ ]:
# importing the libraryies needed for NN

import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
# assigning the voloobary size

voc_size=10000

In [ ]:
messages=x.copy()

messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hillari',
 'chuck todd buzzfe donald trump polit favor breitbart',
 'monica lewinski clinton sex scandal set american crime stori',
 'rob reiner trump mental unstabl breitbart',
 'abort pill order rise latin american nation zika alert new york time',
 'nuke un histor treati ban nuclear weapon',
 'exclus islam state support vow shake west follow manchest terrorist massacr breitbart',
 'humili hillari tri hide camera caught min ralli',
 'andrea tantaro fox news claim retali sex harass complaint new york time',
 'hillari clinton becam hawk new york time',
 'chuck todd buzzfe eic publish fake news breitbart',
 'bori johnson brexit leader fumbl new york time',
 'texa oil field rebound price lull job left behind new york time',
 'bayer deal monsanto follow agribusi trend rais worri farmer new york time',
 'russia move ban jehovah wit extremist new york time',
 'still danger zone januari th',
 'open thread u elect',
 'democrat gutierrez blame chicago gun violenc nra breitbart',
 'avoid peanut avoid allergi bad strategi new york time',
 'mri show detail imag week unborn babi breitbart',
 'best kind milk dairi',
 'ryan locht drop speedo usa retail new york time',
 'conserv urg session clean obama civil right divis breitbart',
 'intern inquiri seal fate roger ail fox new york time',
 'press tv debat duff lebanon hezbollah aoun presid video',
 'samsung combust galaxi note unveil new smartphon new york time',
 'poland vow referendum migrant quota amidst eu pressur public voic heard breitbart',
 'spark inner revolut',
 'studi half car crash involv driver distract cell phone breitbart',
 'trump elect spark individu collect heal',
 'ep fade black jimmi church w laura eisenhow restor balanc video',
 'cognit true islam book review',
 'donald trump win elect biggest miracl us polit histori',
 'mind eat way fight bing new york time',
 'major potenti impact corpor tax overhaul new york time',
 'wonder glp like day elect',
 'maker world smallest machin award nobel prize chemistri new york time',
 'massiv anti trump protest union squar nyc live stream',
 'review lion bring tear lost boy wipe dri googl new york time',
 'u gener islam state chemic attack impact u forc',
 'juri find oregon standoff defend guilti feder conspiraci gun charg',
 'clinton campaign stun fbi reportedli reopen probe hillari clinton email',
 'penc speak anti abort ralli new york time',
 'berni sander say media trump gutless polit coward',
 'make briquett daili wast',
 'treason nyt vow reded report',
 'dress like woman mean new york time',
 'ella brennan still feed lead new orlean new york time',
 'press asia agenda obama tread lightli human right new york time',
 'democrat percent chanc retak senat new york time',
 'judg spank transgend obsess obama lie redflag news',
 'u diplomat urg strike assad syria new york time',
 'franken call independ investig trump putin crush breitbart',
 'louisiana simon bile u presidenti race tuesday even brief new york time',
 'turkey threaten open migrant land passag europ row dutch',
 'huma weiner dog hillari',
 'colin kaepernick start black panther inspir youth camp wow',
 'trump immigr polici explain new york time',
 'mari tyler moor mourn dick van dyke star new york time',
 'poison',
 'trump fan ralli across nation support presid new york time',
 'fox biz report help bash clinton ralli cover trump pack event day',
 'fiction podcast worth listen new york time',
 'mike birbiglia tip make small hollywood anywher new york time',
 'invest strategist forecast collaps timelin last gasp econom cycl come',
 'venezuela muzzl legislatur move closer one man rule new york time',
 'whether john mccain mitt romney donald trump democrat alway run war women tactic destroy republican candid',
 'breitbart news daili trump boom breitbart',
 'white hous confirm gitmo transfer obama leav offic',
 'poll voter heard democrat elect candid breitbart',
 'migrant confront judgment day old deport order new york time',
 'n u yale su retir plan fee new york time',
 'technocraci real reason un want control internet',
 'american driver regain appetit ga guzzler new york time',
 'hillari clinton build million war chest doubl donald trump new york time',
 'trump catch sick report snuck interview priceless respons',
 'senat contact russian govern week',
 'imag perfectli illustr struggl dakota access pipelin',
 'washington state take refuge muslim rest countri take refuge muslim breitbart',
 'ncaa big keep watch eye texa bathroom bill breitbart',
 'massiv espn financi subscrib loss drag disney first quarter sale breitbart',
 'megyn kelli contract set expir next year prime big show new york time',
 'teacher suspend allow student hit trump pinata cinco de mayo',
 'break trump express concern anthoni weiner illeg access classifi info month ago truthfe',
 'snap share leap debut investor doubt valu vanish new york time',
 'clinton campaign chair dinner top doj offici one day hillari benghazi hear',
 'tv seri first femal mlb pitcher can one low rate season breitbart',
 'seek best fit women final four return friday sunday new york time',
 'propos canadian nation bird ruffl feather new york time',
 'review beyonc make lemonad marit strife new york time',
 'trump ask sharp increas militari spend offici say new york time',
 'waterg smoke gun email discuss clean obama hillari email',
 'chapo trap hous new left wing podcast flagrant rip right stuff',
 'taiwan respond china send carrier taiwan strait new york time',
 'mother octob surpris hous card come tumbl',
 'explos assang pilger interview us elect expect riot hillari win',
 'telescop ate astronomi track surpass hubbl new york time',
 'close afghan pakistani border becom humanitarian crisi new york time',
 'tv anchor arriv white hous lunch donald trump breitbart',
 'pelosi republican tell trump bring dishonor presid breitbart',
 'beauti prehistor world earth wasteland',
 'ignor trump news week learn new york time',
 'donald trump unveil plan famili bid women vote new york time',
 'montana democrat vote bill ban sharia law call repugn breitbart',
 'monsanto tribun go happen',
 'offici simon bile world best gymnast new york time',
 'liter hurt brain read econom idioci emit trumpkin libertarian',
 'u n secretari gener complain mass reject global favor nation',
 'trump bollywood ad meant sway indian american voter hilari fail video',
 'fbi find previous unseen hillari clinton email weiner laptop',
 'year american journalist kill conspiraci theori syria proven fact',
 'report illeg alien forego food stamp stay trump radar',
 'make netherland great hahaha spread worldwid',
 'four kill injur jerusalem truck ram terror attack',
 'leader salut comrad newt brutal megyn sic kelli beatdown play game',
 'student black colleg got beaten mace protest kkk david duke',
 'despit strict gun control one child youth shot everi day ontario',
 'rise internet fan bulli new york time',
 'newli vibrant washington fear trump drain cultur new york time',
 'fed hold interest rate steadi plan slower increas new york time',
 'battl unesco',
 'latest test white hous pull easter egg roll new york time',
 'burlesqu dancer fire investig secret servic trump assassin tweet breitbart',
 'clinton haiti',
 'cuomo christi parallel path top troubl got new york time',
 'top place world allow visit',
 'new studi link fluorid consumpt hypothyroid weight gain wors',
 'jame matti secretari offens',
 'black church burn spray paint vote trump',
 'sear agre sell craftsman stanley black amp decker rais cash new york time',
 'takata chief execut resign financi pressur mount new york time',
 'goodby good black sabbath new york time',
 'teen geisha doll gang bust arm robberi breitbart',
 'mohamad khwei anoth virginia man palestinian american muslim charg terror',
 'price obamacar replac nobodi wors financi breitbart',
 'va fail properli examin thousand veteran',
 'trump famili alreadi sworn secreci fake moon land soon',
 'sport writer nfl great jim brown decad civil right work eras say nice thing donald trump breitbart',
 'watch tv excus republican skip donald trump convent new york time',
 'open letter trump voter told like',
 'comment power corpor lobbi quietli back hillari nobodi talk runsinquicksand',
 'hijack end peac libyan airlin land malta new york time',
 'like girl girl geniu new york time',
 'scientist say canadian bacteria fossil may earth oldest new york time',
 'pro govern forc advanc syria amid talk u russia cooper new york time',
 'cancer agenc fire withhold carcinogen glyphos document',
 'work walk minut work new york time',
 'steve harvey talk hous presid elect trump new york time',
 'coalit u troop fight mosul offens come fire',
 'uk citizen war hero get cheap pre fab hous muslim colon get taxpay fund luxuri council home',
 'vet fight war fed demand money back illeg refuge keep money',
 'mr trump wild ride new york time',
 'fbi director comey bamboozl doj congress clinton',
 'food natur unclog arteri prevent heart attack',
 'death two state solut',
 'comment parent date asleep car cop arriv kill facespac',
 'donald trump team show sign post elect moder new york time',
 'miami beach tri tame raucou street fishbowl drink stay new york time',
 'doctor mysteri found dead summit breakthrough cure cancer',
 'donald trump unsink candid new york time',
 'shock new mock hillari ad campaign warn take us war enlistforh fightforh dieforh',
 'exclus famili slain border patrol agent brian terri say eric holder among real crimin respons',
 'trump tell report wall work ask israel breitbart',
 'america surviv next year',
 'commission start press cleveland indian logo new york time',
 'un plan implant everyon biometr id drill',
 'trump attack senat credibl gorsuch comment new york time',
 'clinton advisor lose leak email hillari illeg activ',
 'art laffer paul ryan perfect right breitbart',
 'donald trump blame econom crash',
 'pokemon go player inadvert stop peopl commit suicid japan',
 'california senat race tale divers flail g p new york time',
 'exclus sourc say megyn kelli would welcom back fox news',
 'break preced obama envoy deni extens past inaugur day new york time',
 'brexit vote go monti python may offer clue new york time',
 'blind mystic predict bad news trump',
 'total vet fail left wing snowden fan girl realiti winner get access nsa secret',
 'somalia u escal shadow war new york time',
 'free care bless victim orlando nightclub attack new york time',
 'durabl democrat counti countri could go trump',
 'fed challeng rais rate may existenti new york time',
 'russia intent attack anyon absurd say vladimir putin',
 'f investig errant flight involv harrison ford new york time',
 'fed rais key interest rate cite strengthen economi new york time',
 'la expresi n lo siguient ya es la utilizada lo siguient en el castellano',
 'trump berat news media new strategi need cover new york time',
 'u drone strike target taliban leader new york time',
 'u intellig expect al qaeda attack monday new york virginia texa',
 'told cannabi great revers alzheim',
 'report megyn kelli kick nbc show kardashian famili interview',
 'local percent may rich think new york time',
 'dr david duke mark collett uk collett explain duke trump victori would chang polit forev',
 'statement senat well fargo chief deepli sorri new york time',
 'cnn statement distanc network buzzfe fake news dossier breitbart',
 'c e ponder new game trump rule new york time',
 'spicer bradi stolen jersey anoth bad press breitbart',
 'scaredi cat investig peopl enjoy fear new york time',
 'left vision',
 'showdown loom u question chines deal german chip design new york time',
 'trump administr take harder tack trade china new york time',
 'pew american trust level feder govern plummet histor low breitbart',
 'islam state support former nation guardsman plead guilti terror charg virginia',
 'spicer report go rais hand like big boy girl breitbart',
 'leader applaud gorsuch confirm win pro life movement',
 'newstick',
 'french vogu march cover featur transgend model new york time',
 'trump veer parti line gun control new york time',
 'oligarchi prepar groundwork steal elect',
 'ya hay reencuentro de operaci n triunfo que edicion de operaci n triunfo',
 'chatsworth hous tale five centuri new york time',
 'uncomfort love affair donald trump new england patriot new york time',
 'john mccain withdraw support donald trump disclosur record new york time',
 'strang unend limbo egypt hosni mubarak new york time',
 'poverti rose u hous district obama presid',
 'huma abedin seek fbi immun deal',
 'singl mom escap friend zone one non date time new york time',
 'boe suit futur spaceflight new spacesuit design breitbart',
 'trump float oliv branch might keep part health law new york time',
 'wapo tri compar elizabeth warren break senat rule milo shut violent riot breitbart',
 'crumpl school bu leav chattanooga daze new york time',
 'die came back life incred messag human',
 'fight nation african american museum new york time',
 'father manchest suicid bomber arrest libya breitbart',
 'secret true leader',
 'muslim demand local walk dog public violat sharia disrespect',
 'hillari campaign bed pac staff donat k fbi agent wife investig',
 'still tri flip elector colleg block trump win',
 'al sharpton dem point appeal archi bunker trump voter breitbart',
 'think mani doom sayer trump get offic',
 'democrat jump session resign band wagon breitbart',
 'alt right architect glenn beck open fire alt right grave threat republ audio tweet',
 'politic justic protect hillari',
 'north carolina satur surpris reel hurrican matthew new york time',
 'live love submit memori new york time',
 'achiev mind work medit cushion requir new york time',
 'world first zero emiss hydrogen power passeng train unveil germani',
 'confus chip credit card get line new york time',
 'brook trump side foreign leader us presid israel russia breitbart',
 'toxic air home get rid natur',
 'connecticut reader report record voter registr inspir trump',
 'germani react merkel trump visit could lot wors new york time',
 'justin rose outduel henrik stenson golf gold medal new york time',
 'iceland water cure new york time',
 'shorten l train shutdown month new york time',
 'time presid decid new york time',
 'u n relief offici call crisi aleppo apex horror new york time',
 'berkeley treat violent anti speech left like kkk',
 'statist propaganda mani syrian us regim chang kill',
 'self help guru jame altuch own thing new york time',
 'trump religi liberti order give session major leeway breitbart',
 'demoledor amparo contra salgado keiko congresista',
 'era trump china presid champion econom global new york time',
 'sad saga john walker lindh rebel without clue',
 'court disagre michigan vote recount new york time',
 'berni sander feud democrat leadership heat new york time',
 'shortest power explan trump victori ever seen',
 'russia look popul far east wimp need appli new york time',
 'johnson amend trump vow destroy explain new york time',
 'donald trump march life full support',
 'polic offici found dead long island suicid suspect new york time',
 'radic chang store world global market readi',
 'like make showbiz best friend new york time',
 'trump nomin neil gorsuch suprem court new york time',
 'bidder cast doubt serious mexican border wall project',
 'stake us elect',
 'israel approv addit fund settlement west bank new york time',
 'tx gov abbott sign legisl could put sheriff sanctuari citi jail breitbart',
 'donald trump hold thank ralli cincinnati announc pick defens secretari new york time',
 'lawmak look bipartisanship health care new york time',
 'insid conserv push state amend constitut new york time',
 'donald trump tell n r hillari clinton want let violent crimin go free new york time',
 'pope franci trump japan tuesday brief new york time',
 'mayorsstand day tout support illeg immigr',
 'trump campaign celebr',
 'democrat drag jeff session confirm fight breitbart',
 'break news podesta brother pedo ring mr trump drain swamp v guerrilla economist',
 'la frase destacada del debat de investidura',
 'confus jihad hirabah build peac world',
 'lazi liber journalist smear bannon',
 'australia close detent center manu island still accept asylum seeker new york time',
 'politico hillari clinton run breitbart',
 'giant lynx make ador sound whenev human rub face',
 'minnesota cop found guilti philando castil shoot trial',
 'million american kill minut',
 'wayn madsen cia alway serv interest wall street',
 'novemb daili contrarian read',
 'flashback report obama campaign rep talk iran hama',
 'lesseroftwoevil',
 'aya cash first time ate veget new york time',
 'trump advis say isra settlement illeg',
 'serena william prevail open problem new york time',
 'soul man sam moor honor perform trump inaugur',
 'ferrel came back bush destroy trump video',
 'chines govern concern tough talk trump cabinet breitbart',
 'billionair report seiz hong kong hotel taken china new york time',
 'easi know link',
 'homebodi find ultim home offic new york time',
 'ann coulter unload paul ryan deepli unpopular obamacar bill breitbart',
 'transgend bathroom debat turn person vermont high school new york time',
 'obama hillari want libya gaddafi toppl kill',
 'alert former soro associ warn pro wrong gold silver skyrocket like',
 'hillari panick fbi weiner email',
 'chaotic minut trump defend fine tune machin new york time',
 'one polic shift patrol anxiou america new york time',
 'fight ghost fascist aid real one',
 'monday even brief brexit abort game throne new york time',
 'eu increas brexit bill demand billion billion',
 'arianna huffington sleep revolut start home new york time',
 'iranian missil accident destroy iranian ship aim syria',
 'sonoma counti california vote creat largest gmo free zone america',
 'fbi comey wikileak intellig porn journal breitbart',
 'clare waight keller name first femal design givenchi new york time',
 'realiti face black canadian nation shame',
 'top nfl draft prospect caleb brantley charg punch woman face breitbart',
 'video pacif crest trail associ lavoy finicim murder',
 'life lesson man seen death',
 'trump g p work win repeal obama health act new york time',
 'atlant goldberg confid trump handl matter life death breitbart',
 'orthodox rabbi support trump',
 'nuclear tension us russia reach danger point',
 'gambia join south africa burundi exodu intern crimin court',
 'peyton man golf presid trump sunday',
 'obama urg donald trump send signal uniti minor group women new york time',
 'like miracl woman give birth use ovari frozen sinc childhood new york time',
 'uconn recip success run run run new york time',
 'assang final afford opportun give statement rape accus',
 'hillari puppet show much hillari care god omiss word',
 'stock market gone high problem new york time',
 'john kerri reject suggest u involv turkey coup new york time',
 'trump aid stephen miller u absolut sovereign right determin cannot enter countri breitbart',
 'year old russian girl speak languag',

In [ ]:
# onehot encoding

onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[4217, 9263, 7782, 7195, 410, 2187, 8888, 1864, 3865, 7743],
 [2398, 5959, 2908, 6234, 5828, 1860, 4942],
 [2677, 3503, 3838, 5014],
 [6500, 1635, 6655, 4038, 9901, 1103],
 [4717, 5828, 5803, 3544, 4350, 9573, 5828, 8047, 4662, 9451],
 [6341,
  317,
  9452,
  6764,
  6893,
  7709,
  253,
  1059,
  8566,
  7524,
  6836,
  5639,
  5340,
  6199,
  4942],
 [7853, 1180, 927, 5294, 9475, 9739, 5979, 2872, 859, 1366, 6271],
 [8635, 7718, 1441, 7938, 8882, 3255, 7709, 3828, 859, 1366, 6271],
 [3835, 6949, 6212, 7784, 1200, 1031, 9787, 3850, 7709, 4239],
 [6962, 163, 1619, 8721, 9562, 1493, 3979, 1981],
 [7883, 9551, 4717, 8431, 4912, 2116, 8073, 5457, 2427, 3209, 1670],
 [4038, 2573, 410, 1031, 7709, 8882],
 [6056, 2800, 5276, 1716, 8313, 8696, 728, 7130, 8550],
 [519, 6363, 5647, 6019, 7045, 1327, 4679, 859, 1366, 6271],
 [1304, 6424, 1529, 6424, 1586, 859, 1366, 6271],
 [29, 2183, 368, 9772, 6859, 3444, 6557, 4646, 886, 9861],
 [3461, 9546, 5959],
 [4458, 307, 3182, 6529, 7709, 7499, 8862, 4942],
 [119, 9395, 2908, 3535, 1088, 4875, 8595, 1559, 9573],
 [4566, 9536, 7709, 2669, 4246, 4942],
 [6892, 1432, 8414, 9502, 717, 8595, 5133, 1366, 7818, 859, 1366, 6271],
 [8039, 2309, 8684, 8976, 7879, 3632, 7024],
 [5340, 7368, 6990, 4376, 989, 6176, 976, 7399, 6269, 3214, 5893, 4942],
 [7207, 5959, 6753, 3295, 3317, 1741, 7958, 9586],
 [7794, 3331, 4594, 7491, 5353, 7454, 3535, 2047, 7417, 859, 1366, 6271],
 [5959, 2908, 4882, 4892, 859, 1366, 6271],
 [4458, 307, 3182, 7981, 8831, 7076, 7491, 4942],
 [5799, 8220, 790, 7667, 7386, 859, 1366, 6271],
 [564, 7477, 7534, 8916, 2502, 9112, 6768, 8278, 8580, 859, 1366, 6271],
 [5916, 4225, 9145, 7399, 8934, 5776, 3792, 2360, 7474, 859, 1366, 6271],
 [8882, 1886, 7879, 7499, 3476, 2590, 859, 1366, 6271],
 [5345, 4104, 464, 9377, 5958],
 [7076, 3781, 722, 3480],
 [3910, 4339, 8091, 9171, 6869, 8338, 3092, 4942],
 [9748, 5413, 9748, 7261, 3861, 3684, 859, 1366, 6271],
 [2344, 1526, 8486, 5581, 5040, 947, 287, 4942],
 [3528, 6762, 17, 1706],
 [3288, 1481, 5834, 2401, 5401, 2087, 859, 1366, 6271],
 [4902, 1932, 8895, 7473, 3835, 3259, 4884, 5602, 4942],
 [5854, 9301, 1553, 3039, 7103, 8944, 4594, 859, 1366, 6271],
 [5034, 5578, 2902, 6539, 103, 949, 9079, 4731, 6199],
 [8690, 8685, 8775, 5174, 4161, 859, 8305, 859, 1366, 6271],
 [7844, 989, 39, 7680, 7618, 3742, 3082, 122, 1372, 3454, 9936, 4942],
 [386, 5527, 989],
 [7828, 6022, 4648, 1793, 2539, 7849, 6391, 7990, 8395, 4942],
 [7709, 3480, 386, 2788, 4181, 4797],
 [8096, 5743, 2639, 6874, 6856, 3839, 8193, 1175, 8325, 4700, 6199],
 [2196, 5775, 7368, 5292, 8980],
 [6529, 7709, 927, 3480, 1566, 5867, 4038, 7499, 3989],
 [1408, 3915, 2139, 2358, 5024, 859, 1366, 6271],
 [519, 3484, 8155, 1996, 1066, 3507, 859, 1366, 6271],
 [6069, 5199, 9927, 4348, 3480],
 [4106, 2371, 5614, 4496, 3356, 1005, 7323, 2415, 859, 1366, 6271],
 [8936, 6664, 7709, 9281, 9654, 6859, 5079, 5458, 9647],
 [8980, 91, 5260, 1799, 1685, 2892, 45, 200, 2053, 859, 1366, 6271],
 [722, 723, 7368, 6990, 5219, 2089, 8155, 722, 5129],
 [3764, 7045, 7551, 6567, 2684, 8762, 9017, 7440, 6869, 6868],
 [2908, 2965, 7307, 3461, 2487, 5180, 411, 5959, 2908, 1797],
 [9836, 9881, 6664, 6892, 9586, 859, 1366, 6271],
 [6173, 7814, 9767, 8696, 7709, 1090, 7499, 6700],
 [1311, 1009, 9379, 8012],
 [7438, 6283, 989, 8714, 4899],
 [4171, 9927, 5828, 1752, 859, 1366, 6271],
 [5130, 2651, 5345, 4427, 5517, 859, 4003, 859, 1366, 6271],
 [5034, 7346, 4239, 3835, 4480, 2160, 7664, 4884, 859, 1366, 6271],
 [3910, 1697, 4934, 1608, 1869, 859, 1366, 6271],
 [3955, 6514, 6379, 2745, 3835, 9558, 9428, 7491],
 [722, 41, 1932, 1903, 9407, 2383, 859, 1366, 6271],
 [7519, 3775, 7323, 318, 7709, 2327, 2891, 4942],
 [5074, 3357, 3090, 722, 5979, 2095, 8317, 7195, 6033, 859, 1366, 6271],
 [8437, 5867, 7076, 7680, 6192, 7374, 4155, 3248, 6648],
 [2648, 9242, 8823, 5959],
 [7149, 2065, 2747, 2639, 8699, 2375, 4159, 1155, 9123],
 [7709, 4519, 8406, 6532, 859, 1366, 6271],
 [8317, 4168, 3415, 4507, 1358, 5415, 8721, 7011, 859, 1366, 6271],
 [1918],
 [7709, 9398, 9586, 983, 5133, 4376, 4731, 859, 1366, 6271],
 [4594, 9264, 4899, 4576, 4268, 2908, 9586, 8685, 7709, 9772, 2008, 4348],
 [3544, 8649, 9694, 4849, 859, 1366, 6271],
 [6043, 6920, 9691, 1311, 7116, 9452, 4965, 859, 1366, 6271],
 [8128, 445, 1715, 9695, 9996, 6090, 9700, 2216, 9503, 2129],
 [7152, 2804, 9592, 1886, 2242, 3708, 6906, 6646, 859, 1366, 6271],
 [9418,
  776,
  1442,
  7041,
  9265,
  6529,
  7709,
  3910,
  444,
  8169,
  6586,
  2469,
  2935,
  2576,
  6699,
  2710],
 [4942, 7491, 9379, 7709, 3350, 4942],
 [5141, 4217, 4022, 8523, 3408, 3835, 9918, 278],
 [7570, 414, 9936, 3910, 3480, 2710, 4942],
 [7680, 8276, 1368, 4348, 2771, 6822, 8414, 859, 1366, 6271],
 [6496, 722, 7422, 613, 8662, 1441, 3420, 859, 1366, 6271],
 [2771, 8721, 6685, 2309, 2054, 1172, 9701],
 [8595, 7849, 7314, 4765, 9300, 7856, 859, 1366, 6271],
 [5959, 2908, 7434, 9772, 6586, 6799, 3088, 6529, 7709, 859, 1366, 6271],
 [7709, 742, 1888, 4899, 6181, 9144, 6192, 3502],
 [1869, 2407, 7883, 5276, 5040],
 [5581, 483, 7792, 1362, 4646, 886, 9861],
 [2966, 6990, 5163, 6379, 9556, 2079, 8759, 5163, 6379, 9556, 4942],
 [8654, 6234, 6461, 5971, 1660, 564, 5639, 5543, 4942],
 [8936, 359, 5249, 2786, 1458, 766, 9654, 5397, 4359, 6755, 4942],
 [9862, 4913, 1601, 4875, 13, 5421, 4105, 7774, 6234, 1526, 859, 1366, 6271],
 [6148, 5198, 2858, 4636, 3654, 7709, 7225, 2231, 9491, 1595],
 [5070, 7709, 4265, 2246, 1767, 9242, 4221, 886, 7568, 7352, 284, 3689, 430],
 [9267, 7171, 701, 1592, 2697, 2570, 6329, 6726, 859, 1366, 6271],
 [2908, 2965, 7964, 2159, 5701, 1887, 2573, 3708, 4348, 5959, 3070, 428],
 [5578, 5244, 5397, 8738, 2581, 5329, 4281, 3708, 3669, 9216, 4111, 4942],
 [5734, 3528, 5185, 2469, 955, 3891, 1394, 3903, 1394, 859, 1366, 6271],
 [4362, 4394, 5133, 1028, 8412, 2068, 859, 1366, 6271],
 [8980, 8632, 1311, 4367, 8305, 7938, 859, 1366, 6271],
 [7709, 4351, 855, 47, 2116, 3981, 2573, 9767, 859, 1366, 6271],
 [3792, 6959, 6869, 1797, 5526, 7473, 3835, 5959, 1797],
 [7350, 1816, 4217, 859, 8278, 1720, 8649, 9453, 4988, 4884, 2835],
 [6747, 7303, 5628, 735, 7900, 6747, 9321, 859, 1366, 6271],
 [1794, 3248, 7617, 4217, 725, 2129, 5026],
 [5214, 7260, 5380, 9144, 4038, 3480, 1971, 9270, 5959, 927],
 [5139, 5144, 9148, 1226, 3462, 7203, 859, 1366, 6271],
 [9546, 6586, 1822, 7789, 8702, 9441, 7548, 859, 1366, 6271],
 [5578, 6688, 8505, 5141, 4217, 4802, 6529, 7709, 4942],
 [7738, 6699, 2997, 7709, 5260, 6305, 4731, 4942],
 [1998, 6929, 2371, 8418, 9217],
 [3946, 7709, 7491, 5040, 3590, 859, 1366, 6271],
 [6529, 7709, 4161, 1441, 4067, 7063, 2469, 1692, 859, 1366, 6271],
 [6716, 3910, 1692, 5543, 7879, 7121, 2230, 3775, 6341, 4942],
 [9145, 1191, 5735, 641],
 [2573, 3357, 3090, 2371, 3528, 3116, 859, 1366, 6271],
 [6208, 3576, 7537, 8056, 2216, 369, 4136, 3029, 9117],
 [722, 6496, 3523, 723, 8793, 8337, 8334, 4407, 8862, 5133],
 [7709, 938, 3277, 107, 1132, 3223, 8595, 414, 2315, 6426, 6199],
 [3461, 7045, 4560, 1131, 5959, 2908, 1797, 9242, 6489],
 [4105, 8595, 4381, 1635, 7440, 8060, 2383, 9176, 7141],
 [4899, 4221, 9875, 6988, 181, 3359, 5445, 7709, 5067],
 [1311, 2562, 6390, 9230, 5238, 1212],
 [3891, 1635, 3401, 9605, 4836, 6945, 4972, 2089],
 [7667, 603, 8369, 9033, 3350, 9862, 2957, 4913, 1531, 8531, 7088],
 [4636, 2639, 1847, 210, 8968, 1797, 9281, 9255, 6314, 3130],
 [7048, 4369, 6869, 1172, 3708, 3369, 4159, 7871, 7890, 4348, 9407],
 [9502, 9701, 9398, 7950, 859, 1366, 6271],
 [3326, 7557, 2966, 503, 7709, 4660, 9141, 859, 1366, 6271],
 [3538, 5690, 8041, 9216, 6688, 1441, 8333, 47, 859, 1366, 6271],
 [8327, 9762],
 [9332, 8104, 5141, 4217, 2013, 6976, 8061, 4390, 859, 1366, 6271],
 [5635, 2480, 5014, 318, 8431, 251, 7709, 888, 7743, 4942],
 [2908, 5968],
 [2427, 8277, 8618, 5255, 5701, 3473, 210, 859, 1366, 6271],
 [5701, 7165, 2371, 2858, 1934],
 [859, 7828, 1031, 8056, 4794, 9219, 2636, 4822, 3948],
 [2013, 6754, 3523, 3342],
 [2639, 6856, 4489, 4423, 5608, 1692, 7709],
 [7800, 1006, 164, 5373, 3668, 2639, 1492, 8347, 3792, 5622, 859, 1366, 6271],
 [2891, 1529, 6147, 1408, 5249, 122, 5764, 859, 1366, 6271],
 [497, 1463, 2639, 5118, 859, 1366, 6271],
 [1067, 727, 3590, 3342, 3692, 8617, 6111, 4942],
 [4067, 7409, 5581, 9492, 6906, 9838, 8595, 9556, 6868, 4972],
 [2502, 2972, 974, 9023, 3948, 5249, 4942],
 [2617, 6426, 6877, 8206, 28, 1737],
 [7709, 4067, 2160, 9558, 8705, 7076, 6854, 6192, 9530],
 [2805,
  1799,
  1503,
  6390,
  1026,
  9237,
  6339,
  3259,
  4884,
  1994,
  4197,
  9767,
  8753,
  6511,
  6529,
  7709,
  4942],
 [5971, 5578, 4965, 6699, 1295, 6529, 7709, 3372, 859, 1366, 6271],
 [7076, 8888, 7709, 414, 5319, 9927],
 [8213, 7125, 1996, 9677, 2864, 8635, 5959, 9023, 2864, 7689],
 [1944, 18, 531, 3012, 9869, 6192, 4673, 859, 1366, 6271],
 [9927, 9443, 9443, 2110, 859, 1366, 6271],
 [1749, 9767, 4394, 1771, 1496, 9352, 8418, 2735, 859, 1366, 6271],
 [6338, 5276, 5129, 2072, 2383, 3841, 2864, 722, 8882, 3830, 859, 1366, 6271],
 [1029, 4077, 5014, 5637, 5993, 3789, 69],
 [1994, 1809, 7, 1994, 859, 1366, 6271],
 [6270, 7144, 2864, 4217, 4731, 3480, 7709, 859, 1366, 6271],
 [1178, 722, 3368, 2358, 2884, 3342, 2129, 5014],
 [7437,
  8362,
  6586,
  7504,
  3838,
  41,
  6754,
  586,
  4217,
  9556,
  8046,
  3838,
  5025,
  9869,
  4023,
  6227,
  1327],
 [5180, 2358, 6586, 3538, 4846, 1642, 8635, 4221, 6379, 6461, 1642],
 [6177, 7709, 8395, 295, 859, 1366, 6271],
 [3461, 2649, 2187, 1686, 1887, 1043, 2908],
 [181, 5748, 7910, 9461, 7097, 6081, 2089],
 [4662, 2601, 6990, 7164],
 [8213, 1035, 9702, 3900, 4648, 3260, 8505, 1635, 3143],
 [6529, 7709, 2087, 1526, 3970, 7623, 3480, 1004, 859, 1366, 6271],
 [6241, 5428, 6753, 2159, 7441, 1801, 1671, 5458, 5445, 859, 1366, 6271],
 [454, 2023, 3304, 903, 1458, 2210, 3783, 1029],
 [6529, 7709, 3946, 2710, 859, 1366, 6271],
 [8369, 859, 2956, 5959, 3277, 2965, 9478, 5163, 4038, 6586, 3818, 2903, 8997],
 [5340,
  4067,
  9589,
  7789,
  8052,
  5261,
  1496,
  6747,
  9767,
  3522,
  5703,
  6926,
  8721,
  5883,
  3502],
 [7709, 2997, 4899, 3559, 1994, 4351, 4919, 4942],
 [944, 6560, 5421, 4105],
 [4900, 2747, 5034, 788, 3223, 9905, 859, 1366, 6271],
 [2309, 1441, 5189, 3444, 9970, 2645, 6257],
 [7709, 2089, 1869, 9212, 3307, 8213, 859, 1366, 6271],
 [2908, 4421, 6555, 1641, 1797, 5959, 4221, 1650],
 [8307, 1912, 4196, 3288, 7160, 4884, 4942],
 [6529, 7709, 8091, 2216, 1793],
 [1229, 5735, 2002, 3825, 8481, 290, 4562, 1120, 312],
 [6679, 1869, 2095, 4982, 1169, 6016, 8183, 1882, 859, 1366, 6271],
 [5340, 3271, 9767, 9862, 4913, 6764, 9514, 8635, 4594, 7491],
 [5070, 9092, 3835, 1195, 1444, 7431, 5215, 764, 4348, 859, 1366, 6271],
 [790, 1692, 5735, 4727, 8969, 9352, 9855, 6501, 859, 1366, 6271],
 [1588, 2232, 2804, 3861, 7491, 7709],
 [236,
  5180,
  6426,
  8278,
  1720,
  2423,
  9398,
  9443,
  6825,
  203,
  3838,
  886,
  8099,
  8431],
 [9936, 722, 8036, 6311, 6586, 859, 1366, 6271],
 [9942, 8532, 9135, 9162, 6396, 1328, 2089, 859, 1366, 6271],
 [3180, 3910, 3559, 8759, 346, 5735, 7709],
 [3538, 2509, 3792, 9216, 9352, 3074, 859, 1366, 6271],
 [8882, 8209, 2089, 8584, 6754, 9767, 8503, 2327],
 [8743, 318, 4397, 2629, 2539, 4436, 3401, 859, 1366, 6271],
 [3538, 3792, 8308, 8041, 9216, 9208, 7378, 5829, 859, 1366, 6271],
 [7739,
  9101,
  6496,
  7544,
  1567,
  2868,
  7083,
  7739,
  5629,
  7544,
  1567,
  4381,
  1550,
  4795],
 [7709, 2658, 7491, 8696, 859, 3684, 2077, 8685, 859, 1366, 6271],
 [722, 402, 1903, 3869, 289, 7667, 859, 1366, 6271],
 [722, 9674, 1971, 2710, 2984, 2089, 6610, 859, 1366, 9492, 564],
 [5319, 9697, 6390, 7324, 557],
 [4899, 9862, 4913, 4660, 6332, 1526, 3131, 4067, 9144],
 [6073, 1697, 9352, 3562, 8066, 859, 1366, 6271],
 [8670,
  6314,
  3130,
  8598,
  4326,
  7437,
  4326,
  6532,
  3130,
  7709,
  9152,
  6764,
  5554,
  7499,
  9024],
 [9593, 1869, 1304, 6424, 1529, 4549, 5509, 859, 1366, 6271],
 [8305, 9593, 5470, 5879, 3182, 7076, 7491, 5872, 4942],
 [4524, 7492, 8698, 859, 7088, 7709, 6646, 859, 1366, 6271],
 [6826, 43, 9958, 2875, 5581, 3861, 5034, 4942],
 [5794, 1114, 318, 290, 4393, 503, 859, 1366, 6271],
 [8278, 9779],
 [5190, 4957, 722, 4024, 5173, 4225, 1386, 353, 9817, 859, 1366, 6271],
 [7709, 9379, 5163, 5692, 4567, 8643, 5628, 859, 1366, 6271],
 [1116, 8595, 5486, 6365, 9017, 5276, 8355, 8684, 3669, 4942],
 [7368, 6990, 4376, 3174, 5133, 3276, 3767, 8762, 4972, 6868, 9492],
 [6826, 4899, 5735, 3792, 7240, 9927, 6234, 2892, 9443, 4942],
 [7667, 3677, 3307, 4022, 927, 6338, 6542, 4695],
 [9610],
 [5294, 7386, 1508, 8685, 6156, 6379, 7340, 859, 1366, 6271],
 [7709, 222, 9739, 7951, 6869, 1172, 859, 1366, 6271],
 [9189, 4715, 2918, 2127, 3480],
 [2868, 9156, 3842, 9491, 254, 6496, 3983, 5235, 9850, 9491, 254, 6496, 3983],
 [9655, 4217, 4982, 1278, 8966, 859, 1366, 6271],
 [8106, 6893, 9976, 6529, 7709, 859, 6930, 4571, 859, 1366, 6271],
 [776, 1442, 7162, 4376, 6529, 7709, 6334, 5375, 859, 1366, 6271],
 [3290, 6489, 5453, 8705, 3780, 7124, 859, 1366, 6271],
 [6002, 9310, 722, 4217, 9587, 3835, 4731],
 [2648, 9372, 5734, 3461, 5520, 4225],
 [6655, 3484, 8185, 1298, 464, 3708, 8757, 9702, 6271, 859, 1366, 6271],
 [5210, 5064, 6595, 2380, 859, 8516, 9817, 4942],
 [7709, 9683, 3291, 9016, 3503, 6461, 4547, 4703, 2230, 859, 1366, 6271],
 [1767,
  6753,
  1788,
  4596,
  6584,
  5070,
  1869,
  6646,
  4071,
  5048,
  2522,
  9270,
  4942],
 [8471, 3040, 4339, 9918, 9861, 4155, 859, 1366, 6271],
 [4004, 5487, 8635, 6542, 5481, 6451, 7664],
 [2358, 5133, 1158, 8595, 5931, 859, 1366, 6271],
 [719, 6269, 1120, 9494, 6557, 4938, 4942],
 [8431, 5775, 7667],
 [9556, 4846, 6073, 1809, 8823, 1372, 1442, 7121, 1686],
 [5959, 2965, 4849, 4857, 5261, 3434, 8698, 3461, 5261, 660, 318],
 [5345, 6753, 8034, 2410, 1847, 2528, 7709, 927],
 [2710, 8514, 9263, 3536, 3344, 6550, 3416, 7709, 414, 4942],
 [8066, 234, 5409, 6744, 7709, 3838, 278],
 [3910, 8053, 8895, 1408, 7559, 6861, 4942],
 [6861,
  4884,
  4458,
  9526,
  2815,
  7076,
  5014,
  6861,
  4884,
  8647,
  5046,
  4388,
  1720,
  7743],
 [3858, 890, 5644, 5959],
 [1059, 4089, 5062, 7617, 8776, 6575, 3167, 859, 1366, 6271],
 [5458, 6893, 1728, 6105, 859, 1366, 6271],
 [5258, 1408, 1994, 5828, 1560, 5093, 859, 1366, 6271],
 [2371, 5397, 3636, 7165, 3321, 7125, 4420, 5188, 4161, 3554],
 [2182, 353, 750, 725, 3838, 7951, 859, 1366, 6271],
 [9919, 7709, 994, 8860, 7667, 4038, 4731, 4919, 8882, 4942],
 [8088, 3231, 1327, 3838, 8995, 5748],
 [5183, 7989, 4899, 5375, 414, 6211, 2375, 7709],
 [3554, 9561, 5339, 7709, 1934, 346, 3307, 3948, 859, 1366, 6271],
 [6037, 9310, 4279, 3467, 800, 7282, 4886, 4730, 859, 1366, 6271],
 [9934, 1516, 3783, 859, 1366, 6271],
 [6717, 568, 5188, 6552, 284, 859, 1366, 6271],
 [6271, 4731, 9761, 859, 1366, 6271],
 [722, 6496, 8789, 2573, 3775, 7548, 6452, 3687, 696, 859, 1366, 6271],
 [3097, 5581, 2522, 6664, 2368, 8278, 9927, 9255],
 [5920, 6712, 234, 9638, 4038, 5447, 5554, 1635],
 [4452, 4576, 3850, 2013, 7737, 321, 6511, 859, 1366, 6271],
 [7709, 7010, 4232, 8414, 7119, 8895, 519, 9619, 4942],
 [9826, 3620, 6615, 640, 2713, 8136],
 [5020, 7709, 5628, 4731, 5837, 2216, 4407, 859, 1366, 6271],
 [3348, 9453, 776, 9440, 6341, 4138, 1016, 6501],
 [4165, 8935, 8295, 1692, 8308, 859, 1366, 6271],
 [6173, 7814, 5912, 3910, 9079, 2849, 859, 1366, 6271],
 [4403, 7125, 6526, 7709, 9152, 3774, 709],
 [8882, 4987, 249, 4151, 6498, 1699, 2077, 1735, 859, 1366, 6271],
 [8220, 2973, 7709, 989, 2576, 6532, 859, 1366, 6271],
 [6529, 7709, 1508, 6542, 1744, 4376],
 [2837, 2573, 3304, 903, 8572, 6061, 1120, 52, 859, 1366, 6271],
 [9146, 5554, 6775, 2371, 4407, 4091, 6782],
 [9927, 1311, 8403, 3528, 1298, 859, 1366, 6271],
 [7709, 2872, 3125, 3307, 926, 4165, 859, 1366, 6271],
 [785, 5575, 2570, 4359, 7164, 7789, 3559, 716],
 [6625, 4038, 3480],
 [4919, 1637, 2535, 9869, 9246, 976, 3632, 859, 1366, 6271],
 [2783, 6775, 747, 3970, 1893, 346, 937, 4588, 8401, 6026, 5803, 4942],
 [6529, 7709, 5690, 2444, 9586, 1249, 4343, 9188, 3601, 3523, 859, 1366, 6271],
 [7502, 4987, 2814, 4703, 8532, 859, 1366, 6271],
 [4788, 4902, 7638, 6990, 2973, 6944, 859, 1366, 6271],
 [6529,
  7709,
  2997,
  6496,
  9920,
  5959,
  2908,
  2054,
  9261,
  2522,
  5883,
  5735,
  9942,
  859,
  1366,
  6271],
 [4579, 6327, 7709, 312, 8317, 6033, 859, 1366, 6271],
 [6873, 4348, 6712, 4376, 4221, 4519],
 [7709, 2965, 2911],
 [3910, 766, 4154, 8895, 4022, 2358, 4942],
 [5070,
  7491,
  2104,
  8129,
  2853,
  1855,
  6177,
  7709,
  4660,
  2160,
  3644,
  8492,
  3021],
 [7739, 7200, 521, 599, 2902, 9491, 2723],
 [2182, 9266, 7494, 7434, 531, 2371],
 [3299, 7040, 4381, 7756, 6905],
 [1441, 9546, 6656, 6201, 4879, 6061, 5345, 2884, 9920, 5775, 859, 1366, 6271],
 [2498, 5959, 2908, 8169, 4942],
 [7704, 9176, 1311, 2522, 3050, 4314, 7664, 1037, 9923],
 [1069, 3260, 3304, 8762, 9348, 9933, 5921, 7649],
 [9772, 8595, 1635, 7],
 [4460, 1223, 4552, 444, 8670, 8041, 3559, 1801],
 [6858, 9379, 1256, 8056],
 [5496, 4899, 3835, 2965, 9002, 2864, 8661, 2625],
 [3948],
 [3293, 5622, 5397, 6271, 5144, 7857, 859, 1366, 6271],
 [7709, 5658, 9767, 1957, 9246, 4221],
 [2327, 4441, 2315, 7076, 7408, 859, 1366, 6271],
 [2661, 6906, 4103, 3415, 8922, 6271, 7709, 764],
 [2889, 5487, 8635, 6066, 2576, 7709, 6199],
 [5173, 5276, 2246, 2069, 2864, 7709, 80, 4942],
 [655, 4899, 8975, 4652, 7665, 9593, 5064, 5628, 859, 1366, 6271],
 [3547, 4424, 1031],
 [9090, 7045, 454, 1327, 278, 859, 1366, 6271],
 [9495, 6894, 7978, 4196, 3288, 4549, 4733, 2972, 5543, 4942],
 [6379, 5639, 2902, 2557, 9919, 5501, 2671, 3040, 859, 1366, 6271],
 [3835, 5959, 2054, 4938, 3841, 622, 1635],
 [7818, 3174, 1200, 3828, 9478, 6338, 6623, 4886, 3471, 2724, 9927],
 [5959, 5019, 3461, 9242, 1797],
 [9876, 7, 7709, 2684, 810, 9438, 4496, 859, 1366, 6271],
 [3708, 2837, 1600, 8052, 607, 944, 859, 1366, 6271],
 [2358, 6749, 2370, 7782, 8721, 3708],
 [6610, 7195, 6033, 790, 6892, 7088, 4476, 859, 1366, 6271],
 [3082, 47, 790, 5543, 4846, 2011, 2011],
 [6978, 5120, 60, 989, 2747, 1327, 859, 1366, 6271],
 [4717, 2040, 6751, 2576, 4717, 2268, 8500, 2383],
 [5945, 3559, 6679, 1692, 2021, 9189, 9754, 9942, 464, 944],
 [3461, 2187, 4278, 9674, 3525, 6378, 4942],
 [7337, 8727, 279, 9623, 5397, 8738, 9817, 4376, 859, 1366, 6271],
 [6825, 9923, 2639, 4394, 5133, 218],
 [5701, 1503, 6499, 3683, 4445, 3306, 6868, 409, 5828, 9923, 4942],
 [6199, 2920, 5087, 8012, 3828, 3232, 7315, 6972],
 [6542, 250, 6906, 709, 4662],
 [7709, 8183, 1882, 1994, 927, 4745, 3835, 4703, 644, 859, 1366, 6271],
 [2082, 9460, 2540, 7709, 5035, 5059, 6542, 4662, 4942],
 [172, 8913, 4376, 7709],
 [3632, 5658, 4038, 8882, 777, 4104, 3536],
 [2165, 6255, 8780, 3089, 1524, 939, 5854, 5883, 4165],
 [8838, 6906, 7282, 4731, 7709, 1394],
 [3835, 1932, 6529, 7709, 735, 1941, 8385, 7618, 9817, 2469, 859, 1366, 6271],
 [9927, 5867, 5828, 7119, 7800, 3637, 7792, 134, 6867, 1662, 859, 1366, 6271],
 [1601, 7478, 4679, 8169, 8169, 8169, 859, 1366, 6271],
 [7260, 955, 9561, 3330, 7119, 9593, 3306, 3970],
 [5959, 5784, 1526, 595, 5959, 8532, 5919, 7901, 1344],
 [6966, 4091, 9790, 2671, 7408, 859, 1366, 6271],
 [776, 2269, 8334, 7386, 722, 2539, 8437, 6807, 859, 1366, 6271],
 [7709, 7782, 5431, 2450, 722, 3291, 467, 4884, 7659, 6800, 9660, 8759, 4942],
 [4105, 2771, 7883, 9443, 9881, 9869],
 [7125, 1996, 9677, 2864, 8635, 5959, 9023, 2864],
 [3756, 8809, 4494, 9923, 9127, 859, 1366, 6271],
 [8051, 3932, 2187, 5014, 5871, 1716, 7709, 9263, 4942],
 [7198, 9669, 5276, 2528, 3693, 9915, 1545, 7709, 859, 1366, 6271],
 [6635, 4514, 1327, 4180, 2364, 859, 1366, 6271],
 [2187, 8888, 2908, 1797, 2304, 890, 3241, 9301, 859, 1366, 6271],
 [7137, 4673, 722, 7437, 122, 2147, 2858, 7883, 7900, 9817, 231, 5128],
 [8980, 4977, 6854, 2328, 2543, 3212, 8280, 859, 1366, 6271],
 [6906, 8086, 2837, 612, 9642, 1994],
 [5828, 6557, 7814, 6192, 9958, 1716],
 [4405,
  7323,
  859,
  1366,
  6271,
  927,
  9379,
  7491,
  1606,
  7171,
  1372,
  251,
  3356,
  859,
  1366,
  6271],
 [7478, 3476, 311, 6066, 2908, 4402, 6529, 7709, 764, 4942],

In [ ]:
# embedding part

sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1864 3865 7743]
 [   0    0    0 ... 5828 1860 4942]
 [   0    0    0 ... 3503 3838 5014]
 ...
 [   0    0    0 ... 8313 2558 4942]
 [   0    0    0 ...  859 1366 6271]
 [   0    0    0 ... 1508  290 1692]]

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4217,
       9263, 7782, 7195,  410, 2187, 8888, 1864, 3865, 7743], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
len(embedded_docs),y.shape

(2084, (2084,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((2084, 20), (2084,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=64)

Epoch 1/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 6s 93ms/step - accuracy: 0.7099 - loss: 0.6265 - val_accuracy: 0.8140 - val_loss: 0.4837
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.8417 - loss: 0.3683 - val_accuracy: 0.8677 - val_loss: 0.3168
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.9234 - loss: 0.2334 - val_accuracy: 0.8837 - val_loss: 0.2616
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9484 - loss: 0.1420 - val_accuracy: 0.8852 - val_loss: 0.2692
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9850 - loss: 0.0643 - val_accuracy: 0.8953 - val_loss: 0.2901
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9928 - loss: 0.0295 - val_accuracy: 0.8968 - val_loss: 0.2682
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9936 - loss: 0.0192 - val_accuracy: 0.8997 - val_loss: 0.2594
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9986 - loss: 0.0081 - val_accuracy: 0.8997 - val_loss: 0.3825
Epoch 9/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9986 - loss: 0.0111 - val_accuracy: 0.8881 - val_loss: 0.3391
Epoch 10/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.9993 - loss: 0.0028 - val_accuracy: 0.8924 - val_loss: 0.4369
Epoch 11/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.8953 - val_loss: 0.3841
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.8852 - val_loss: 0.4377
Epoch 13/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accuracy: 1.0000 - loss: 6.9286e-04 - val_accuracy: 0.8924 - val_loss: 0.4743
Epoch 14/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 1.0000 - loss: 5.9804e-04 - val_accuracy: 0.8895 - val_loss: 0.4933
Epoch 15/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 1.0000 - loss: 4.8731e-04 - val_accuracy: 0.8881 - val_loss: 0.4948
Epoch 16/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 1.0000 - loss: 4.1424e-04 - val_accuracy: 0.8779 - val_loss: 0.5091
Epoch 17/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 1.0000 - loss: 3.9477e-04 - val_accuracy: 0.8866 - val_loss: 0.4968
Epoch 18/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 1.0000 - loss: 2.6946e-04 - val_accuracy: 0.8866 - val_loss: 0.5123
Epoch 19/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 2.2211e-04 - val_accuracy: 0.8823 - val_loss: 0.5308
Epoch 20/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 2.0086e-04 - val_accuracy: 0.8808 - val_loss: 0.5383
Epoch 21/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 1.0000 - loss: 1.7659e-04 - val_accuracy: 0.8808 - val_loss: 0.5520
Epoch 22/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 1.7456e-04 - val_accuracy: 0.8765 - val_loss: 0.5601
Epoch 23/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 1.5389e-04 - val_accuracy: 0.8794 - val_loss: 0.5647
Epoch 24/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 1.3897e-04 - val_accuracy: 0.8794 - val_loss: 0.5732
Epoch 25/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 1.0000 - loss: 1.2737e-04 - val_accuracy: 0.8750 - val_loss: 0.5871
Epoch 26/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 1.0000 - loss: 1.1925e-04 - val_accuracy: 0.8794 - val_loss: 0.5888
Epoch 27/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - accuracy: 1.0000 - loss: 1.0721e-04 - val_accuracy: 0.8750 - val_loss: 0.6006
Epoch 28/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 1.1133e-04 - val_accuracy: 0.8721 - val_loss: 0.6077
Epoch 29/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 1.0038e-04 - val_accuracy: 0.8808 - val_loss: 0.6119
Epoch 30/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 9.2358e-05 - val_accuracy: 0.8721 - val_loss: 0.6197
Epoch 31/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 8.6444e-05 - val_accuracy: 0.8721 - val_loss: 0.6221
Epoch 32/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 7.8807e-05 - val_accuracy: 0.8779 - val_loss: 0.6278
Epoch 33/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 7.3799e-05 - val_accuracy: 0.8706 - val_loss: 0.6354
Epoch 34/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 6.9367e-05 - val_accuracy: 0.8750 - val_loss: 0.6397
Epoch 35/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 6.7188e-05 - val_accuracy: 0.8692 - val_loss: 0.6529
Epoch 36/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 1.0000 - loss: 7.3461e-05 - val_accuracy: 0.8692 - val_loss: 0.6496
Epoch 37/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 1.0000 - loss: 6.8688e-05 - val_accuracy: 0.8794 - val_loss: 0.6544
Epoch 38/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 1.0000 - loss: 6.1797e-05 - val_accuracy: 0.8692 - val_loss: 0.6638
Epoch 39/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 1.0000 - loss: 5.3780e-05 - val_accuracy: 0.8779 - val_loss: 0.6622
Epoch 40/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 5.8453e-05 - val_accuracy: 0.8692 - val_loss: 0.6700
Epoch 41/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 1.0000 - loss: 4.8618e-05 - val_accuracy: 0.8692 - val_loss: 0.6713
Epoch 42/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 4.6771e-05 - val_accuracy: 0.8677 - val_loss: 0.6827
Epoch 43/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 4.4508e-05 - val_accuracy: 0.8735 - val_loss: 0.6823
Epoch 44/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 4.3560e-05 - val_accuracy: 0.8692 - val_loss: 0.6890
Epoch 45/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 4.2686e-05 - val_accuracy: 0.8692 - val_loss: 0.6934
Epoch 46/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 4.0458e-05 - val_accuracy: 0.8677 - val_loss: 0.6978
Epoch 47/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - accuracy: 1.0000 - loss: 3.8341e-05 - val_accuracy: 0.8677 - val_loss: 0.7019
Epoch 48/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 67ms/step - accuracy: 1.0000 - loss: 3.7412e-05 - val_accuracy: 0.8663 - val_loss: 0.7074
Epoch 49/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 1.0000 - loss: 3.5174e-05 - val_accuracy: 0.8663 - val_loss: 0.7133
Epoch 50/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 3.3851e-05 - val_accuracy: 0.8663 - val_loss: 0.7195
Epoch 51/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 3.3415e-05 - val_accuracy: 0.8706 - val_loss: 0.7196
Epoch 52/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 3.2532e-05 - val_accuracy: 0.8663 - val_loss: 0.7275
Epoch 53/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 3.0352e-05 - val_accuracy: 0.8663 - val_loss: 0.7291
Epoch 54/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 3.0249e-05 - val_accuracy: 0.8677 - val_loss: 0.7331
Epoch 55/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 2.9666e-05 - val_accuracy: 0.8692 - val_loss: 0.7362
Epoch 56/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 2.8147e-05 - val_accuracy: 0.8634 - val_loss: 0.7445
Epoch 57/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 2.6402e-05 - val_accuracy: 0.8692 - val_loss: 0.7447
Epoch 58/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 2.7638e-05 - val_accuracy: 0.8619 - val_loss: 0.7603
Epoch 59/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 2.6038e-05 - val_accuracy: 0.8677 - val_loss: 0.7491
Epoch 60/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 1.0000 - loss: 2.4582e-05 - val_accuracy: 0.8648 - val_loss: 0.7589
Epoch 61/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 76ms/step - accuracy: 1.0000 - loss: 2.3707e-05 - val_accuracy: 0.8677 - val_loss: 0.7571
Epoch 62/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 1.0000 - loss: 2.2600e-05 - val_accuracy: 0.8634 - val_loss: 0.7660
Epoch 63/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 2.2142e-05 - val_accuracy: 0.8648 - val_loss: 0.7678
Epoch 64/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 2.1307e-05 - val_accuracy: 0.8648 - val_loss: 0.7729
Epoch 65/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 2.1001e-05 - val_accuracy: 0.8663 - val_loss: 0.7751
Epoch 66/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 2.0107e-05 - val_accuracy: 0.8648 - val_loss: 0.7814
Epoch 67/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 2.0015e-05 - val_accuracy: 0.8677 - val_loss: 0.7803
Epoch 68/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 2.0684e-05 - val_accuracy: 0.8619 - val_loss: 0.7880
Epoch 69/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 1.8354e-05 - val_accuracy: 0.8605 - val_loss: 0.7894
Epoch 70/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 1.0000 - loss: 1.8683e-05 - val_accuracy: 0.8663 - val_loss: 0.7905
Epoch 71/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 1.7158e-05 - val_accuracy: 0.8605 - val_loss: 0.8001
Epoch 72/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - accuracy: 1.0000 - loss: 1.7433e-05 - val_accuracy: 0.8619 - val_loss: 0.8031
Epoch 73/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 1.0000 - loss: 1.6723e-05 - val_accuracy: 0.8605 - val_loss: 0.8049
Epoch 74/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 1.0000 - loss: 1.5899e-05 - val_accuracy: 0.8619 - val_loss: 0.8080
Epoch 75/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 1.0000 - loss: 1.5685e-05 - val_accuracy: 0.8590 - val_loss: 0.8164
Epoch 76/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 1.0000 - loss: 1.5312e-05 - val_accuracy: 0.8619 - val_loss: 0.8164
Epoch 77/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 1.4799e-05 - val_accuracy: 0.8619 - val_loss: 0.8209
Epoch 78/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - accuracy: 1.0000 - loss: 1.4386e-05 - val_accuracy: 0.8634 - val_loss: 0.8247
Epoch 79/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 1.4038e-05 - val_accuracy: 0.8619 - val_loss: 0.8275
Epoch 80/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 1.3643e-05 - val_accuracy: 0.8590 - val_loss: 0.8319
Epoch 81/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 1.3351e-05 - val_accuracy: 0.8590 - val_loss: 0.8378
Epoch 82/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 1.0000 - loss: 1.2960e-05 - val_accuracy: 0.8605 - val_loss: 0.8389
Epoch 83/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 1.0000 - loss: 1.2605e-05 - val_accuracy: 0.8590 - val_loss: 0.8447
Epoch 84/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 1.0000 - loss: 1.2501e-05 - val_accuracy: 0.8605 - val_loss: 0.8462
Epoch 85/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - accuracy: 1.0000 - loss: 1.2542e-05 - val_accuracy: 0.8605 - val_loss: 0.8495
Epoch 86/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 1.0000 - loss: 1.1878e-05 - val_accuracy: 0.8590 - val_loss: 0.8589
Epoch 87/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 1.0000 - loss: 1.1736e-05 - val_accuracy: 0.8590 - val_loss: 0.8566
Epoch 88/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 1.0000 - loss: 1.1520e-05 - val_accuracy: 0.8605 - val_loss: 0.8614
Epoch 89/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 1.1261e-05 - val_accuracy: 0.8619 - val_loss: 0.8640
Epoch 90/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 1.0000 - loss: 1.0902e-05 - val_accuracy: 0.8576 - val_loss: 0.8717
Epoch 91/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 1.0000 - loss: 1.0712e-05 - val_accuracy: 0.8547 - val_loss: 0.8677
Epoch 92/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 1.0541e-05 - val_accuracy: 0.8561 - val_loss: 0.8717
Epoch 93/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 73ms/step - accuracy: 1.0000 - loss: 1.0124e-05 - val_accuracy: 0.8590 - val_loss: 0.8762
Epoch 94/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 3s 151ms/step - accuracy: 1.0000 - loss: 1.0205e-05 - val_accuracy: 0.8619 - val_loss: 0.8818
Epoch 95/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 1.0000 - loss: 1.0620e-05 - val_accuracy: 0.8590 - val_loss: 0.8848
Epoch 96/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 9.5364e-06 - val_accuracy: 0.8590 - val_loss: 0.8832
Epoch 97/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 9.3060e-06 - val_accuracy: 0.8561 - val_loss: 0.8900
Epoch 98/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 9.1547e-06 - val_accuracy: 0.8561 - val_loss: 0.8884
Epoch 99/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 1.0000 - loss: 8.9678e-06 - val_accuracy: 0.8590 - val_loss: 0.8931
Epoch 100/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 1.0000 - loss: 8.6636e-06 - val_accuracy: 0.8561 - val_loss: 0.9012

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[344,  47],
       [221,  76]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6104651162790697